/*
 * This file was generated by the Gradle "init" task.
 */

allprojects {
    group = "com.mekong.warehouse"
    version = "1.0-SNAPSHOT"
}

plugins {
    java
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "scala")
    apply(plugin = "maven-publish")

    repositories {
        mavenLocal()
        maven("http://repo.hortonworks.com/content/repositories/releases/")
        maven ("http://repo.maven.apache.org/maven2")
    }

    dependencies {
        implementation("org.apache.avro:avro:1.9.0")
        implementation("org.apache.spark:spark-core_2.11:2.4.1")
        implementation("org.apache.spark:spark-sql_2.11:2.4.1")
        implementation("com.thoughtworks.paranamer:paranamer:2.8")
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_1_8
    }
}
